In [1]:
import pandas as pd
import numpy as np

In [2]:
import ast

In [3]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [4]:
movies = movies.merge(credits , on="title")

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [6]:
movies = movies [['movie_id','genres','title','overview','keywords','cast','crew']]

In [7]:
movies.head()

,movie_id,genres,title,overview,keywords,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies.isnull().sum()

movie_id    0
genres      0
title       0
overview    3
keywords    0
cast        0
crew        0
dtype: int64

In [9]:
movies.dropna(inplace=True)

In [10]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [11]:
def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [12]:
movies['genres'] = movies['genres'].apply(convert)

In [13]:
movies ['keywords'] = movies ['keywords'].apply(convert)

In [14]:
movies.head()

,movie_id,genres,title,overview,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]",Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]",John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
def convert3(obj):
  L = []
  counter = 0
  for i in ast.literal_eval(obj):
    if counter !=3:
      L.append(i['name'])
      counter +=1
    else:
      break
  return L

In [16]:
movies['cast'] = movies['cast'].apply(convert3)

In [17]:
movies.head()

,movie_id,genres,title,overview,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]",Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]",John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
def fetch_dir(obj):
  L = []
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
      L.append(i['name'])
      break
  return L

In [19]:
movies['crew'] = movies['crew'].apply(fetch_dir)

In [20]:
movies.head()

,movie_id,genres,title,overview,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]",Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]",John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [21]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [22]:
movies.head()

,movie_id,genres,title,overview,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [23]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [24]:
movies['tags'] = movies["overview"]+ movies['keywords'] + movies["genres"] + movies["cast"] + movies["crew"]

In [25]:
movies.head()

,movie_id,genres,title,overview,keywords,cast,crew,tags
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,"[Action, Adventure, Crime]",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,"[Action, Adventure, ScienceFiction]",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [26]:
new_df = movies[["movie_id","title","tags"]]

In [27]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [28]:
new_df["tags"] = new_df["tags"].apply(lambda x:" ".join(x))

/tmp/ipykernel_2808/1578042357.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].apply(lambda x:" ".join(x))

In [29]:
new_df["tags"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [30]:
new_df["tags"] = new_df["tags"].apply(lambda x:x.lower())

/tmp/ipykernel_2808/3481706753.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].apply(lambda x:x.lower())

In [31]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words="english")

In [33]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [34]:
def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

In [35]:
new_df["tags"] = new_df["tags"].apply(stem)

/tmp/ipykernel_2808/825579503.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].apply(stem)

In [36]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [37]:
vectors = cv.fit_transform(new_df["tags"]).toarray()

In [38]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [39]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [40]:
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
similarity = cosine_similarity(vectors).shape

In [42]:
similarity = cosine_similarity(vectors)

In [43]:
list(similarity[0])

[np.float64(1.0000000000000002),
 np.float64(0.08346223261119858),
 np.float64(0.08603090020146065),
 np.float64(0.0734718358370645),
 np.float64(0.1892994097121204),
 np.float64(0.10838874619051501),
 np.float64(0.04024218182927669),
 np.float64(0.14673479641335554),
 np.float64(0.05923488777590923),
 np.float64(0.0978231976089037),
 np.float64(0.10259783520851541),
 np.float64(0.09464970485606021),
 np.float64(0.09037128496931669),
 np.float64(0.04499212706658476),
 np.float64(0.12988108336653278),
 np.float64(0.06282808624375433),
 np.float64(0.07894736842105264),
 np.float64(0.13977653617040256),
 np.float64(0.09493290614465533),
 np.float64(0.0830812984794528),
 np.float64(0.058038100008800934),
 np.float64(0.10968169942141635),
 np.float64(0.0662266178532522),
 np.float64(0.08740748201220976),
 np.float64(0.0533380747062665),
 np.float64(0.05101627678885769),
 np.float64(0.15389675281277312),
 np.float64(0.18693292157876878),
 np.float64(0.116543309349613),
 np.float64(0.065033247714309),
 np.float64(0.06684847767323797),
 np.float64(0.15907119074394446),
 np.float64(0.08520286456846099),
 np.float64(0.09733285267845754),
 np.float64(0.0),
 np.float64(0.09933992677987831),
 np.float64(0.17119059581558146),
 np.float64(0.07894736842105264),
 np.float64(0.08111071056538127),
 np.float64(0.08226127456606226),
 np.float64(0.07694837640638656),
 np.float64(0.16563698349810535),
 np.float64(0.0),
 np.float64(0.09086217008485092),
 np.float64(0.03382550457458692),
 np.float64(0.08240856434303293),
 np.float64(0.1391037210186643),
 np.float64(0.19672236884115843),
 np.float64(0.08447772061910234),
 np.float64(0.0582716546748065),
 np.float64(0.11295649894498103),
 np.float64(0.07987230638308718),
 np.float64(0.14673479641335554),
 np.float64(0.042973504259354006),
 np.float64(0.031219527052723135),
 np.float64(0.07038153430777869),
 np.float64(0.13834289277321493),
 np.float64(0.024182541670333724),
 np.float64(0.06748819059987714),
 np.float64(0.07254762501100116),
 np.float64(0.018367958959266125),
 np.float64(0.23179316248638276),
 np.float64(0.0837707816583391),
 np.float64(0.08175191193132876),
 np.float64(0.029617443887954616),
 np.float64(0.019529164171612674),
 np.float64(0.02249606353329238),
 np.float64(0.16452254913212452),
 np.float64(0.1204950466257556),
 np.float64(0.02649064714130088),
 np.float64(0.076004188790721),
 np.float64(0.07336739820667779),
 np.float64(0.13710212427677043),
 np.float64(0.0331133089266261),
 np.float64(0.2024645717996314),
 np.float64(0.10390486669322622),
 np.float64(0.07175473098524099),
 np.float64(0.014394823400711486),
 np.float64(0.050669459193814),
 np.float64(0.0623109738595896),
 np.float64(0.050464733268936676),
 np.float64(0.11020775375559676),
 np.float64(0.076004188790721),
 np.float64(0.17996850826633903),
 np.float64(0.12361284651454937),
 np.float64(0.1141270638770543),
 np.float64(0.07098727864204515),
 np.float64(0.11128297681493143),
 np.float64(0.09037128496931669),
 np.float64(0.05757929360284594),
 np.float64(0.06131393394849658),
 np.float64(0.16692446522239718),
 np.float64(0.0623109738595896),
 np.float64(0.07098727864204515),
 np.float64(0.1873171623163388),
 np.float64(0.14048787173725413),
 np.float64(0.07694837640638656),
 np.float64(0.06952346619889824),
 np.float64(0.07509392614826384),
 np.float64(0.02666903735313325),
 np.float64(0.06765100914917384),
 np.float64(0.07694837640638656),
 np.float64(0.12462194771917919),
 np.float64(0.07987230638308718),
 np.float64(0.05564148840746572),
 np.float64(0.1037571695799112),
 np.float64(0.0623109738595896),
 np.float64(0.061806423257274694),
 np.float64(0.14509525002200235),
 np.float64(0.06488856845230502),
 np.float64(0.04499212706658476),
 np.float64(0.15018785229652767),
 np.float64(0.07694837640638656),
 np.float64(0.043355498476206004),
 np.float64(0.04588314677411236),
 np.float64(0.043747863925980714),
 np.float64(0.04783648732349399),
 np.float64(0.05923488777590923),
 np.float64(0.03364315551262445),
 np.float64(0.043355498476206004),
 np.float64(0.0),
 np.float64(0.11128297681493143),
 np.float64(0.116543309349613),
 np.float64(0.1124803176664619),
 np.float64(0.06748819059987714),
 np.float64(0.07843304784240032),
 np.float64(0.13334518676566626),
 np.float64(0.14601068654819693),
 np.float64(0.0),
 np.float64(0.09269795493186431),
 np.float64(0.027036903521793755),
 np.float64(0.10526315789473685),
 np.float64(0.04499212706658476),
 np.float64(0.028239124736245257),
 np.float64(0.12977713690461004),
 np.float64(0.0),
 np.float64(0.023414645289542353),
 np.float64(0.0301237616564389),
 np.float64(0.12824729401064427),
 np.float64(0.12072654548783007),
 np.float64(0.04499212706658476),
 np.float64(0.08740748201220976),
 np.float64(0.08471737420873576),
 np.float64(0.08671099695241201),
 np.float64(0.05006261743217589),
 np.float64(0.019252140716412975),
 np.float64(0.016222142113076255),
 np.float64(0.05564148840746572),
 np.float64(0.09733285267845754),
 np.float64(0.15511334686589626),
 np.float64(0.16426202236672155),
 np.float64(0.2029530274475215),
 np.float64(0.08346223261119858),
 np.float64(0.07868894753646337),
 np.float64(0.06131393394849658),
 np.float64(0.02043797798283219),
 np.float64(0.05990422978731538),
 np.float64(0.09933992677987831),
 np.float64(0.13369695534647594),
 np.float64(0.06362847629757779),
 np.float64(0.11712303424679457),
 np.float64(0.03181423814878889),
 np.float64(0.0331133089266261),
 np.float64(0.051298917604257706),
 np.float64(0.08000711205939975),
 np.float64(0.04588314677411236),
 np.float64(0.12515654358043973),
 np.float64(0.09037128496931669),
 np.float64(0.17521916101261562),
 np.float64(0.08830215713766959),
 np.float64(0.10650358071057624),
 np.float64(0.02271554252121273),
 np.float64(0.21239769762143662),
 np.float64(0.023174488732966077),
 np.float64(0.07792865001991967),
 np.float64(0.07098727864204515),
 np.float64(0.02913582733740325),
 np.float64(0.0),
 np.float64(0.024455799402225926),
 np.float64(0.07254762501100116),
 np.float64(0.022075539284417398),
 np.float64(0.04499212706658476),
 np.float64(0.11707322644771176),
 np.float64(0.07038153430777869),
 np.float64(0.17521916101261562),
 np.float64(0.050669459193814),
 np.float64(0.05901671065234752),
 np.float64(0.15389675281277312),
 np.float64(0.022075539284417398),
 np.float64(0.1147078669352809),
 np.float64(0.08447772061910234),
 np.float64(0.04891159880445185),
 np.float64(0.047324852428030105),
 np.float64(0.07878168645790681),
 np.float64(0.0),
 np.float64(0.05923488777590923),
 np.float64(0.05195243334661311),
 np.float64(0.036973693332326786),
 np.float64(0.057353933467640436),
 np.float64(0.08671099695241201),
 np.float64(0.10882143751650175),
 np.float64(0.0),
 np.float64(0.03181423814878889),
 np.float64(0.08346223261119858),
 np.float64(0.04947706959952935),
 np.float64(0.07443229275647868),
 np.float64(0.11092107999698035),
 np.float64(0.07694837640638656),
 np.float64(0.12262786789699316),
 np.float64(0.06765100914917384),
 np.float64(0.07509392614826384),
 np.float64(0.024455799402225926),
 np.float64(0.06622661785325219),
 np.float64(0.05901671065234752),
 np.float64(0.0),
 np.float64(0.06622661785325219),
 np.float64(0.06488856845230502),
 np.float64(0.08520286456846099),
 np.float64(0.03823595564509363),
 np.float64(0.09197090092274487),
 np.float64(0.1777046633277277),
 np.float64(0.047324852428030105),
 np.float64(0.07987230638308718),
 np.float64(0.10390486669322622),
 np.float64(0.060833032924035954),
 np.float64(0.046829290579084706),
 np.float64(0.0301237616564389),
 np.float64(0.08226127456606226),
 np.float64(0.11037769642208699),
 np.float64(0.1074861545850028),
 np.float64(0.09183979479633063),
 np.float64(0.0),
 np.float64(0.11128297681493143),
 np.float64(0.1037571695799112),
 np.float64(0.08594700851870801),
 np.float64(0.076004188790721),
 np.float64(0.11470786693528087),
 np.float64(0.0662266178532522),
 np.float64(0.11092107999698035),
 np.float64(0.09125667909262308),
 np.float64(0.046829290579084706),
 np.float64(0.07894736842105264),
 np.float64(0.08111071056538127),
 np.float64(0.09269795493186431),
 np.float64(0.09197090092274487),
 np.float64(0.08111071056538127),
 np.float64(0.07647191129018727),
 np.float64(0.0),
 np.float64(0.04456565178215865),
 np.float64(0.13834289277321493),
 np.float64(0.0),
 np.float64(0.04188539082916955),
 np.float64(0.020277677641345318),
 np.float64(0.06335829046432676),
 np.float64(0.06952346619889824),
 np.float64(0.0),
 np.float64(0.11164843913471803),
 np.float64(0.0533380747062665),
 np.float64(0.01769980813511972),
 np.float64(0.06131393394849658),
 np.float64(0.20395079136182276),
 np.float64(0.024182541670333724),
 np.float64(0.10650358071057624),
 np.float64(0.09733285267845754),
 np.float64(0.0),
 np.float64(0.02742042485535409),
 np.float64(0.0989541391990587),
 np.float64(0.06488856845230502),
 np.float64(0.052631578947368425),
 np.float64(0.029617443887954616),
 np.float64(0.08830215713766959),
 np.float64(0.07098727864204515),
 np.float64(0.02782074420373286),
 np.float64(0.021119430154775586),
 np.float64(0.08977310580745099),
 np.float64(0.1433848336691011),
 np.float64(0.06243905410544627),
 np.float64(0.053099424405359155),
 np.float64(0.11707322644771176),
 np.float64(0.09269795493186431),
 np.float64(0.0),
 np.float64(0.065033247714309),
 np.float64(0.04456565178215865),
 np.float64(0.02742042485535409),
 np.float64(0.018367958959266125),
 np.float64(0.019529164171612674),
 np.float64(0.0781166566864507),
 np.float64(0.025976216673306556),
 np.float64(0.02742042485535409),
 np.float64(0.04588314677411236),
 np.float64(0.06243905410544627),
 np.float64(0.04947706959952935),
 np.float64(0.08885233166386385),
 np.float64(0.029617443887954616),
 np.float64(0.1433848336691011),
 np.float64(0.10526315789473685),
 np.float64(0.038778336716474064),
 np.float64(0.044151078568834795),
 np.float64(0.0),
 np.float64(0.05945550264670635),
 np.float64(0.1711905958155815),
 np.float64(0.09365858115816939),
 np.float64(0.07024393586862707),
 np.float64(0.028239124736245257),
 np.float64(0.06578947368421054),
 np.float64(0.19007487139298027),
 np.float64(0.08111071056538127),
 np.float64(0.10876595882948199),
 np.float64(0.06765100914917384),
 np.float64(0.06243905410544627),
 np.float64(0.03065696697424829),
 np.float64(0.15018785229652765),
 np.float64(0.10012523486435178),
 np.float64(0.05484084971070818),
 np.float64(0.0),
 np.float64(0.08346223261119858),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.09933992677987831),
 np.float64(0.03065696697424829),
 np.float64(0.0),
 np.float64(0.2105263157894737),
 np.float64(0.029617443887954616),
 np.float64(0.024182541670333724),
 np.float64(0.09933992677987831),
 np.float64(0.05647824947249051),
 np.float64(0.027036903521793755),
 np.float64(0.02742042485535409),
 np.float64(0.07894736842105264),
 np.float64(0.10012523486435178),
 np.float64(0.08998425413316952),
 np.float64(0.106676149412533),
 np.float64(0.024455799402225926),
 np.float64(0.0967301666813349),
 np.float64(0.046348977465932154),
 np.float64(0.06917144638660747),
 np.float64(0.04543108504242546),
 np.float64(0.0),
 np.float64(0.04891159880445185),
 np.float64(0.04947706959952935),
 np.float64(0.08226127456606226),
 np.float64(0.16122923187750418),
 np.float64(0.019252140716412975),
 np.float64(0.029617443887954616),
 np.float64(0.023174488732966077),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.06131393394849658),
 np.float64(0.076004188790721),
 np.float64(0.04891159880445185),
 np.float64(0.0),
 np.float64(0.02742042485535409),
 np.float64(0.04120428217151646),
 np.float64(0.021677749238103002),
 np.float64(0.03650267163704923),
 np.float64(0.09037128496931669),
 np.float64(0.0),
 np.float64(0.0602475233128778),
 np.float64(0.031219527052723135),
 np.float64(0.020942695414584774),
 np.float64(0.07509392614826384),
 np.float64(0.09544271444636668),
 np.float64(0.09909250441117726),
 np.float64(0.023414645289542353),
 np.float64(0.07509392614826384),
 np.float64(0.05647824947249051),
 np.float64(0.0),
 np.float64(0.12977713690461004),
 np.float64(0.126673647984535),
 np.float64(0.050669459193814),
 np.float64(0.09567297464698798),
 np.float64(0.047324852428030105),
 np.float64(0.17292861596651865),
 np.float64(0.03797316245786213),
 np.float64(0.061313933948496574),
 np.float64(0.046829290579084706),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.05073825686188038),
 np.float64(0.05195243334661311),
 np.float64(0.0837707816583391),
 np.float64(0.0),
 np.float64(0.043355498476206004),
 np.float64(0.028676966733820218),
 np.float64(0.0),
 np.float64(0.021873931962990357),
 np.float64(0.023662426214015053),
 np.float64(0.0),
 np.float64(0.08740748201220976),
 np.float64(0.026315789473684213),
 np.float64(0.056573571480353566),
 np.float64(0.0301237616564389),
 np.float64(0.0),
 np.float64(0.024738534799764674),
 np.float64(0.05195243334661311),
 np.float64(0.043747863925980714),
 np.float64(0.05195243334661311),
 np.float64(0.0),
 np.float64(0.023662426214015053),
 np.float64(0.09037128496931669),
 np.float64(0.03065696697424829),
 np.float64(0.08226127456606226),
 np.float64(0.0830812984794528),
 np.float64(0.06243905410544627),
 np.float64(0.05564148840746572),
 np.float64(0.0207703246198632),
 np.float64(0.021300716142115247),
 np.float64(0.03244428422615251),
 np.float64(0.0),
 np.float64(0.0978231976089037),
 np.float64(0.0533380747062665),
 np.float64(0.09567297464698798),
 np.float64(0.1411956236812263),
 np.float64(0.029617443887954616),
 np.float64(0.053418342734682205),
 np.float64(0.050669459193814),
 np.float64(0.03244428422615251),
 np.float64(0.03539961627023944),
 np.float64(0.06882472016116853),
 np.float64(0.1124803176664619),
 np.float64(0.023174488732966077),
 np.float64(0.116543309349613),
 np.float64(0.04120428217151646),
 np.float64(0.036973693332326786),
 np.float64(0.06390214842634574),
 np.float64(0.05374307729250139),
 np.float64(0.026315789473684213),
 np.float64(0.055824219567359015),
 np.float64(0.0),
 np.float64(0.050669459193814),
 np.float64(0.024182541670333724),
 np.float64(0.11357771260606365),
 np.float64(0.031219527052723135),
 np.float64(0.0),
 np.float64(0.03539961627023944),
 np.float64(0.0),
 np.float64(0.025649458802128853),
 np.float64(0.12227899701112963),
 np.float64(0.026315789473684213),
 np.float64(0.024738534799764674),
 np.float64(0.057353933467640436),
 np.float64(0.04543108504242546),
 np.float64(0.06390214842634574),
 np.float64(0.0),
 np.float64(0.0989541391990587),
 np.float64(0.023174488732966077),
 np.float64(0.06446025638903101),
 np.float64(0.021300716142115247),
 np.float64(0.10968169942141635),
 np.float64(0.021300716142115247),
 np.float64(0.025031308716087945),
 np.float64(0.03065696697424829),
 np.float64(0.024455799402225926),
 np.float64(0.11587244366483038),
 np.float64(0.060833032924035954),
 np.float64(0.043355498476206004),
 np.float64(0.08603090020146065),
 np.float64(0.043355498476206004),
 np.float64(0.03458572319330373),
 np.float64(0.024182541670333724),
 np.float64(0.1411956236812263),
 np.float64(0.032283269414765066),
 np.float64(0.03244428422615251),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.14509525002200233),
 np.float64(0.10559715077387793),
 np.float64(0.02782074420373286),
 np.float64(0.05945550264670635),
 np.float64(0.04543108504242546),
 np.float64(0.06390214842634574),
 np.float64(0.106676149412533),
 np.float64(0.09269795493186431),
 np.float64(0.0),
 np.float64(0.043747863925980714),
 np.float64(0.13530201829834768),
 np.float64(0.0),
 np.float64(0.05407380704358751),
 np.float64(0.08797691788472335),
 np.float64(0.0978231976089037),
 np.float64(0.0),
 np.float64(0.021873931962990357),
 np.float64(0.12487810821089254),
 np.float64(0.02913582733740325),
 np.float64(0.052631578947368425),
 np.float64(0.07992075789278003),
 np.float64(0.12725695259515557),
 np.float64(0.06657426652986062),
 np.float64(0.0),
 np.float64(0.14159846508095775),
 np.float64(0.09909250441117726),
 np.float64(0.076004188790721),
 np.float64(0.03065696697424829),
 np.float64(0.0),
 np.float64(0.19088542889273336),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.06765100914917384),
 np.float64(0.0),
 np.float64(0.025976216673306556),
 np.float64(0.08175191193132876),
 np.float64(0.13369695534647594),
 np.float64(0.07509392614826384),
 np.float64(0.0),
 np.float64(0.13530201829834768),
 np.float64(0.03458572319330373),
 np.float64(0.255608593705383),
 np.float64(0.10259783520851541),
 np.float64(0.022075539284417398),
 np.float64(0.0989541391990587),
 np.float64(0.09197090092274487),
 np.float64(0.02742042485535409),
 np.float64(0.14843120879858804),
 np.float64(0.04947706959952935),
 np.float64(0.024738534799764674),
 np.float64(0.028239124736245257),
 np.float64(0.0),
 np.float64(0.043747863925980714),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.025031308716087945),
 np.float64(0.024182541670333724),
 np.float64(0.04836508334066745),
 np.float64(0.0),
 np.float64(0.047324852428030105),
 np.float64(0.028239124736245257),
 np.float64(0.0331133089266261),
 np.float64(0.022282825891079324),
 np.float64(0.16742770563222897),
 np.float64(0.05564148840746572),
 np.float64(0.046348977465932154),
 np.float64(0.021300716142115247),
 np.float64(0.0602475233128778),
 np.float64(0.0837707816583391),
 np.float64(0.0978231976089037),
 np.float64(0.1124803176664619),
 np.float64(0.06765100914917384),
 np.float64(0.0),
 np.float64(0.25038669783359574),
 np.float64(0.07509392614826384),
 np.float64(0.10559715077387793),
 np.float64(0.036973693332326786),
 np.float64(0.07098727864204515),
 np.float64(0.05564148840746572),
 np.float64(0.024738534799764674),
 np.float64(0.06362847629757779),
 np.float64(0.08471737420873576),
 np.float64(0.0),
 np.float64(0.11959121830873498),
 np.float64(0.024738534799764674),
 np.float64(0.03771571432023571),
 np.float64(0.0),
 np.float64(0.028676966733820218),
 np.float64(0.0),
 np.float64(0.04499212706658475),
 np.float64(0.02666903735313325),
 np.float64(0.12227899701112963),
 np.float64(0.0),
 np.float64(0.0301237616564389),
 np.float64(0.03604920469572501),
 np.float64(0.03181423814878889),
 np.float64(0.03065696697424829),
 np.float64(0.025649458802128853),
 np.float64(0.08885233166386385),
 np.float64(0.043355498476206004),
 np.float64(0.023918243661746996),
 np.float64(0.025031308716087945),
 np.float64(0.1411956236812263),
 np.float64(0.047324852428030105),
 np.float64(0.06765100914917384),
 np.float64(0.04223886030955117),
 np.float64(0.10743376064838502),
 np.float64(0.0207703246198632),
 np.float64(0.023414645289542353),
 np.float64(0.04543108504242546),
 np.float64(0.05195243334661311),
 np.float64(0.1976738731537168),
 np.float64(0.037463432463267755),
 np.float64(0.14567913668701626),
 np.float64(0.024182541670333724),
 np.float64(0.14567913668701626),
 np.float64(0.24511108480187255),
 np.float64(0.03771571432023571),
 np.float64(0.08111071056538127),
 np.float64(0.024455799402225926),
 np.float64(0.04499212706658476),
 np.float64(0.09464970485606021),
 np.float64(0.025649458802128853),
 np.float64(0.13245323570650439),
 np.float64(0.0301237616564389),
 np.float64(0.06282808624375433),
 np.float64(0.021119430154775586),
 np.float64(0.0),
 np.float64(0.04947706959952935),
 np.float64(0.16059101370939324),
 np.float64(0.09269795493186431),
 np.float64(0.05923488777590923),
 np.float64(0.03627381250550058),
 np.float64(0.02742042485535409),
 np.float64(0.06882472016116853),
 np.float64(0.033463724070512735),
 np.float64(0.09086217008485092),
 np.float64(0.05407380704358751),
 np.float64(0.0662266178532522),
 np.float64(0.025334729596907),
 np.float64(0.0),
 np.float64(0.05775642214923893),
 np.float64(0.0),
 np.float64(0.046829290579084706),
 np.float64(0.058038100008800934),
 np.float64(0.023174488732966077),
 np.float64(0.06390214842634574),
 np.float64(0.03539961627023944),
 np.float64(0.04891159880445185),
 np.float64(0.06131393394849658),

In [44]:
sort=sorted([(i, float(v)) for i ,v in enumerate(similarity[0])],reverse=True,key=lambda x: x[1])[1:6]

In [45]:
def recommend(movies):
  movies_index = new_df[new_df['title'] == movies].index[0]
  distance = similarity[movies_index]
  movies_list = sorted([(i, float(v)) for i ,v in enumerate(distance)],reverse=True,key=lambda x: x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

In [46]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

## Save model files for the Streamlit app

The frontend app loads `model/new_df.pkl` and `model/similarity.pkl`. Run the next cell after training the model in this notebook.

In [ ]:
import os
import pickle

os.makedirs("model", exist_ok=True)

# Keep the same title/tag data used for similarity, plus display fields for the frontend.
model_df = new_df.copy()
model_df["genres"] = movies["genres"].values
model_df["overview"] = movies["overview"].apply(lambda x: " ".join(x) if isinstance(x, list) else x).values
model_df["cast"] = movies["cast"].values
model_df["crew"] = movies["crew"].values
model_df = model_df.reset_index(drop=True)

with open("model/new_df.pkl", "wb") as f:
    pickle.dump(model_df, f)

with open("model/similarity.pkl", "wb") as f:
    pickle.dump(similarity, f)

print("Model files saved successfully.")
print(f"Movies: {len(model_df)}")
print(f"Similarity matrix: {similarity.shape}")